# Generated by Django 2.2.4 on 2019-09-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='imagen')),
                ('excel', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
